version: "3.9"
services:
  backend:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - node_modules:/app/node_modules
      - .:/app
  api:
    image: "r8.im/fofr/become-image@sha256:8d0b076a2aff3904dfcec3253c778e0310a68f78483c4699c7fd800f3051d2b3"
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


volumes:
  node_modules:
